### ISSUE TITLE
Invalid host in request fails with Internal Server Error

### ISSUE THREAD

**Issue by marc-mabe** [mezzio/mezzio-router#25]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.7.0

#### Summary

Requests with and invalid `Host` header value end up in 500 Internal Server Error.
As it's not a valid request the response should be 400 Bad Request.
At our company we get an alert for 5xx errors and so we are getting alerted each time someone send invalid requests like this:

```
[2022-01-04T02:02:50+00:00] [ERR] 500 [GET] https://${ip}/: Laminas\Uri\Exception\InvalidUriPartException: Host "${ip}" is not valid or is not accepted by Laminas\Uri\Http in /app/vendor/laminas/laminas-uri/src/Uri.php:767 Stack trace:
#0 /app/vendor/laminas/laminas-uri/src/Uri.php(339): Laminas\Uri\Uri->setHost()
#1 /app/vendor/laminas/laminas-uri/src/Http.php(218): Laminas\Uri\Uri->parse()
#2 /app/vendor/laminas/laminas-uri/src/Uri.php(165): Laminas\Uri\Http->parse()
#3 /app/vendor/laminas/laminas-http/src/Request.php(204): Laminas\Uri\Uri->__construct()
#4 /app/vendor/laminas/laminas-psr7bridge/src/Laminas/Request.php(42): Laminas\Http\Request->setUri()
#5 /app/vendor/laminas/laminas-psr7bridge/src/Psr7ServerRequest.php(34): Laminas\Psr7Bridge\Laminas\Request->__construct()
#6 /app/vendor/mezzio/mezzio-laminasrouter/src/LaminasRouter.php(85): Laminas\Psr7Bridge\Psr7ServerRequest::toLaminas()
#7 /app/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(37): Mezzio\Router\LaminasRouter->match()
#8 /app/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Mezzio\Router\Middleware\RouteMiddleware->process()
#9 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#10 /app/vendor/mezzio/mezzio-helpers/src/ServerUrlMiddleware.php(30): Laminas\Stratigility\Next->handle()
#11 /app/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Mezzio\Helper\ServerUrlMiddleware->process()
#12 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#13 /app/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(131): Laminas\Stratigility\Next->handle()
#14 /app/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Laminas\Stratigility\Middleware\ErrorHandler->process()
#15 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#16 /app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#17 /app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#18 /app/vendor/mezzio/mezzio-swoole/src/Event/RequestHandlerRequestListener.php(119): Laminas\Stratigility\MiddlewarePipe->handle()
#19 /app/vendor/mezzio/mezzio-swoole/src/Event/EventDispatcher.php(39): Mezzio\Swoole\Event\RequestHandlerRequestListener->__invoke()
#20 /app/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunner.php(135): Mezzio\Swoole\Event\EventDispatcher->dispatch()
#21 [internal function]: Mezzio\Swoole\SwooleRequestHandlerRunner->onRequest()
#22 /app/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunner.php(79): Swoole\Server->start()
#23 /app/vendor/mezzio/mezzio/src/Application.php(68): Mezzio\Swoole\SwooleRequestHandlerRunner->run()
#24 /app/bin/server.php(28): Mezzio\Application->run()
#25 /app/bin/server.php(29): {closure}()
#26 {main}

Next Laminas\Http\Exception\InvalidArgumentException: Invalid URI passed as string (https://${ip}/) in /app/vendor/laminas/laminas-http/src/Request.php:206 Stack trace:
#0 /app/vendor/laminas/laminas-psr7bridge/src/Laminas/Request.php(42): Laminas\Http\Request->setUri()
#1 /app/vendor/laminas/laminas-psr7bridge/src/Psr7ServerRequest.php(34): Laminas\Psr7Bridge\Laminas\Request->__construct()
#2 /app/vendor/mezzio/mezzio-laminasrouter/src/LaminasRouter.php(85): Laminas\Psr7Bridge\Psr7ServerRequest::toLaminas()
#3 /app/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(37): Mezzio\Router\LaminasRouter->match()
#4 /app/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Mezzio\Router\Middleware\RouteMiddleware->process()
#5 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#6 /app/vendor/mezzio/mezzio-helpers/src/ServerUrlMiddleware.php(30): Laminas\Stratigility\Next->handle()
#7 /app/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Mezzio\Helper\ServerUrlMiddleware->process()
#8 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#9 /app/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(131): Laminas\Stratigility\Next->handle()
#10 /app/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Laminas\Stratigility\Middleware\ErrorHandler->process()
#11 /app/vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#12 /app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#13 /app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#14 /app/vendor/mezzio/mezzio-swoole/src/Event/RequestHandlerRequestListener.php(119): Laminas\Stratigility\MiddlewarePipe->handle()
#15 /app/vendor/mezzio/mezzio-swoole/src/Event/EventDispatcher.php(39): Mezzio\Swoole\Event\RequestHandlerRequestListener->__invoke()
#16 /app/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunner.php(135): Mezzio\Swoole\Event\EventDispatcher->dispatch()
#17 [internal function]: Mezzio\Swoole\SwooleRequestHandlerRunner->onRequest()
#18 /app/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunner.php(79): Swoole\Server->start()
#19 /app/vendor/mezzio/mezzio/src/Application.php(68): Mezzio\Swoole\SwooleRequestHandlerRunner->run()
#20 /app/bin/server.php(28): Mezzio\Application->run()
#21 /app/bin/server.php(29): {closure}()
#22 {main} 
```

#### Current behavior

Thrown `Laminas\Uri\Exception\InvalidUriPartException` will be catched by the `ErrorHandler` middleware and returns a 500 Internal Server Error. 

#### How to reproduce

Provide a request with invalid `Host` header value.

#### Expected behavior

The exception should be catched within the `Mezzio\Router\Middleware\RouteMiddleware` and a 400 Bad Request should be returned.

**Comment by weierophinney** [comment]
I'm going to note that this is specific to mezzio-laminasrouter; I've tried this with mezzio-fastroute, and it works fine. The issue is with how laminas-http handles invalid hostnames.

One workaround you can do for now is to create a middleware that you pipe after the existing `ErrorHandler` that looks like the following:

```php
declare(strict_types=1);

namespace App;

use Laminas\Http\Exception\InvalidArgumentException;
use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

class InvalidUriHostMiddleware implements MiddlewareInterface
{
    public function __construct(private ResponseFactoryInterface $responseFactory) {}

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        try {
            return $handler->handle($request);
        } catch (InvalidArgumentException $e) {
            if (false === strpos($e->getMessage(), 'Invalid URI')) {
                throw $e;
            }
        }

        return $this->responseFactory->createResponse(400);
    }
}
```

Honestly, I'm unsure if this is something we can correct easily, because it would require router-specific logic in the error handler at this point to manage. We may need to just document the above solution.
